### ISSUE TITLE
下载了前端项目，已经换了线上接口，vue.config.js也配置了跨域，但是还是提示跨域错误

### ISSUE THREAD

**Issue by tonjies** [gzydong/lumenim#27]
``    // https: true,
    port: 8000,
    proxy: {
      //配置跨域
      '/api': {
        // target: 'http://api.xxxx.com', // 后台接口域名
        target: 'https://im-api.gzydong.club', // 后台接口域名
        ws: true, //如果要代理 websockets，配置这个参数
        secure: true, // 如果是https接口，需要配置这个参数
        changeOrigin: true, //是否跨域
        pathRewrite: {
          '^/api': '/api',
        },
      },
    },
  },`
`

**Comment by gzydong** [comment]
我线上接口做了防盗链了，前端是连接不上的

**Comment by tonjies** [comment]
您好，是这样的，我不会Php相关的技术，感觉部署php后端代码可能部署不起来，请问这种有什么其他的办法吗（发小红包感感谢）&nbsp;


今日早睡．&nbsp;″
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月9日(星期一) 下午3:49
收件人: ***@***.***&gt;; 
抄送: "今日早睡． ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gzydong/LumenIM] 下载了前端项目，已经换了线上接口，vue.config.js也配置了跨域，但是还是提示跨域错误 (Issue #27)





 
我线上接口做了防盗链了，前端是连接不上的

**Comment by gzydong** [comment]
加我QQ837215079
