### ISSUE TITLE
bug:自己显示在对话的左侧，头像也没有了。具体可能与个人信息存储与读取有关系。当做其他人处理了

### ISSUE THREAD

**Issue by aohanhongzhi** [gzydong/lumenim#45]
<img width="1033" alt="image" src="https://github.com/gzydong/LumenIM/assets/37319319/fa8f0c1c-d6b0-45aa-b4f1-bf1492f7852b">

**Comment by gzydong** [comment]
能复现么，我这边没复现

**Comment by aohanhongzhi** [comment]
> 能复现么，我这边没复现

缓存原因，可能。直接忽略吧。后期发现再说。
