### ISSUE TITLE
为啥发送im消息不使用websocket 而是http？

### ISSUE THREAD

**Issue by dingchunqiuzyz** [gzydong/lumenim#81]

**Comment by give0923** [comment]
你要从安全性和可维护性角度出发考虑

**Comment by dingchunqiuzyz** [comment]
> 你要从安全性和可维护性角度出发考虑

im 要做实时聊天啊，安全和协议选择关系不大吧？ websocket可维护性也还好啊

**Comment by give0923** [comment]
1我的意思是你可以从这个方向考虑，2你考虑过ws的稳定性吗？如果发送失败了怎么处理，消息不要啦？可靠性体现在哪里呢？

**Comment by dingchunqiuzyz** [comment]
> 1我的意思是你可以从这个方向考虑，2你考虑过ws的稳定性吗？如果发送失败了怎么处理，消息不要啦？可靠性体现在哪里呢？

太搞笑了吧，ws稳定性有啥问题，http就不失败了？ 失败重试啊

**Comment by dingchunqiuzyz** [comment]
> 1我的意思是你可以从这个方向考虑，2你考虑过ws的稳定性吗？如果发送失败了怎么处理，消息不要啦？可靠性体现在哪里呢？

快把你回复删除了吧 别秀了

**Comment by 1IRVING** [comment]
哈哈哈急了，那你就用你说的去实现啊。谁阻止你了？

**Comment by give0923** [comment]
> > 1我的意思是你可以从这个方向考虑，2你考虑过ws的稳定性吗？如果发送失败了怎么处理，消息不要啦？可靠性体现在哪里呢？
> 
> 快把你回复删除了吧 别秀了

哈哈哈急了，那你就用你说的去实现啊。谁阻止你了？

**Comment by dingchunqiuzyz** [comment]
> > > 1我的意思是你可以从这个方向考虑，2你考虑过ws的稳定性吗？如果发送失败了怎么处理，消息不要啦？可靠性体现在哪里呢？
> > 
> > 
> > 快把你回复删除了吧 别秀了
> 
> 哈哈哈急了，那你就用你说的去实现啊。谁阻止你了？

只是觉得你是来搞笑，有点降智

**Comment by dingchunqiuzyz** [comment]
> > > 1我的意思是你可以从这个方向考虑，2你考虑过ws的稳定性吗？如果发送失败了怎么处理，消息不要啦？可靠性体现在哪里呢？
> > 
> > 
> > 快把你回复删除了吧 别秀了
> 
> 哈哈哈急了，那你就用你说的去实现啊。谁阻止你了？

>> 只是觉得你是来搞笑，有点降智

**Comment by qinshihuang233** [comment]
你脑子不好是吧

**Comment by dingchunqiuzyz** [comment]
> 你脑子不好是吧

呦呵，又来一位脑残

**Comment by qinshihuang233** [comment]
> > 你脑子不好是
> 
> 哎呀，又来烦人

sb

**Comment by dingchunqiuzyz** [comment]
> > 哎呀，又来烦人

别这么说自己，这下都知道你s-b了

**Comment by qinshihuang233** [comment]
> > > 哎呀，又来烦人
> 
> 别这么说自己，这下都知道你s-b了

闭嘴吧曹尼玛傻逼，狗叫什么，废物东西，你爹妈是不是都死了，你太爷爷诈尸是不是给你爹妈拽下去了，傻逼。

**Comment by dingchunqiuzyz** [comment]
> > > > 哎呀，又来烦人
> > 
> > 
> > 别这么说自己，这下都知道你s-b了
> 
> 闭嘴吧曹尼玛傻逼，狗叫什么，废物东西，你爹妈是不是都死了，你太爷爷诈尸是不是给你爹妈拽下去了，傻逼。

没有 ，你爹妈都死了 哈哈哈

**Comment by dingchunqiuzyz** [comment]
> > > > 哎呀，又来烦人
> > 
> > 
> > 别这么说自己，这下都知道你s-b了
> 
> 闭嘴吧曹尼玛傻逼，狗叫什么，废物东西，你爹妈是不是都死了，你太爷爷诈尸是不是给你爹妈拽下去了，傻逼。

再给来个狗叫，快来 1,2,3开始你的狗叫表演

**Comment by 1IRVING** [comment]
> > 你脑子不好是吧
> 
> 呦呵，又来一位脑残

废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急

**Comment by dingchunqiuzyz** [comment]
> > > 你脑子不好是吧
> > 
> > 
> > 呦呵，又来一位脑残
> 
> 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急

本来不想搭理你了 ，你也来狗叫了 ，那你们两个一起叫吧

**Comment by dingchunqiuzyz** [comment]
> > > 你脑子不好是吧
> > 
> > 
> > 呦呵，又来一位脑残
> 
> 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急

很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限

**Comment by give0923** [comment]
> > > > 你脑子不好是吧
> > > 
> > > 
> > > 呦呵，又来一位脑残
> > 
> > 
> > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> 
> 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限

谁没正常？哈哈哈 真的是急了，直接开始乱咬人了，真的是没教好啊。可悲

**Comment by give0923** [comment]
> > > > 你脑子不好是吧
> > > 
> > > 
> > > 呦呵，又来一位脑残
> > 
> > 
> > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> 
> 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限

你这个也叫做技术讨论啊？哈哈哈哈哈 直接破防了骂人了还叫做技术讨论 hhh

**Comment by qinshihuang233** [comment]
> > > > 你脑子不好是吧
> > > 
> > > 
> > > 呦呵，又来一位脑残
> > 
> > 
> > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> 
> 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限

别几把叫了，废物东西，你还技术讨论，，用你那个金针菇跟你在地里烂成泥巴的亲娘讨论去吧

**Comment by dingchunqiuzyz** [comment]
> > > > > 你脑子不好是吧
> > > > 
> > > > 
> > > > 呦呵，又来一位脑残
> > > 
> > > 
> > > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> > 
> > 
> > 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限
> 
> 别几把叫了，废物东西，你还技术讨论，，用你那个金针菇跟你在地里烂成泥巴的亲娘讨论去吧

摸摸狗头，让你叫真叫，很听话的狗，多叫几声

**Comment by dingchunqiuzyz** [comment]
> > > > > 你脑子不好是吧
> > > > 
> > > > 
> > > > 呦呵，又来一位脑残
> > > 
> > > 
> > > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> > 
> > 
> > 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限
> 
> 你这个也叫做技术讨论啊？哈哈哈哈哈 直接破防了骂人了还叫做技术讨论 hhh

看看谁先破防的

**Comment by dingchunqiuzyz** [comment]
> > > > > 你脑子不好是吧
> > > > 
> > > > 
> > > > 呦呵，又来一位脑残
> > > 
> > > 
> > > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> > 
> > 
> > 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限
> 
> 你这个也叫做技术讨论啊？哈哈哈哈哈 直接破防了骂人了还叫做技术讨论 hhh

你呢，websocket稳定和发送失败都搞不定，在这里秀，只是觉得你智商低能力差，不想搭理你还在那里叫唤。

**Comment by dingchunqiuzyz** [comment]
> > > > > 你脑子不好是吧
> > > > 
> > > > 
> > > > 呦呵，又来一位脑残
> > > 
> > > 
> > > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> > 
> > 
> > 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限
> 
> 别几把叫了，废物东西，你还技术讨论，，用你那个金针菇跟你在地里烂成泥巴的亲娘讨论去吧

你是个只会满嘴喷粉的臭傻逼，没钱的话我可以给你出5毛去医院看看是不是小时候吃你妈逼留下的后遗症。

**Comment by give0923** [comment]
> > > > > > 你脑子不好是吧
> > > > > 
> > > > > 
> > > > > 呦呵，又来一位脑残
> > > > 
> > > > 
> > > > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> > > 
> > > 
> > > 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限
> > 
> > 
> > 你这个也叫做技术讨论啊？哈哈哈哈哈 直接破防了骂人了还叫做技术讨论 hhh
> 
> 你呢，websocket稳定和发送失败都搞不定，在这里秀，只是觉得你智商低能力差，不想搭理你还在那里叫唤。

哈哈哈哈哈。这还不是破防了啊？这就是你所谓得正常讨论技术啊？哈哈哈，说到你痛处了吧，一连发了好几个脏话，太可怜了。你是最聪明的 全天下你最聪明

**Comment by dingchunqiuzyz** [comment]
> > > > > > > 你脑子不好是吧
> > > > > > 
> > > > > > 
> > > > > > 呦呵，又来一位脑残
> > > > > 
> > > > > 
> > > > > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> > > > 
> > > > 
> > > > 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限
> > > 
> > > 
> > > 你这个也叫做技术讨论啊？哈哈哈哈哈 直接破防了骂人了还叫做技术讨论 hhh
> > 
> > 
> > 你呢，websocket稳定和发送失败都搞不定，在这里秀，只是觉得你智商低能力差，不想搭理你还在那里叫唤。
> 
> 哈哈哈哈哈。这还不是破防了啊？这就是你所谓得正常讨论技术啊？哈哈哈，说到你痛处了吧，一连发了好几个脏话，太可怜了。你是最聪明的 全天下你最聪明

本来没骂你，你自己凑过来找骂的，你连协议稳定安全，失败怎么处理都不知道 ，就别秀了好吗？也没邀请你过来回答，你一张口给我逗笑了，所以你能力和智商有问题。

**Comment by qinshihuang233** [comment]
> > > > > > > > 你脑子不好是吧
> > > > > > > 
> > > > > > > 
> > > > > > > 呦呵，又来一位脑残
> > > > > > 
> > > > > > 
> > > > > > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> > > > > 
> > > > > 
> > > > > 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限
> > > > 
> > > > 
> > > > 你这个也叫做技术讨论啊？哈哈哈哈哈 直接破防了骂人了还叫做技术讨论 hhh
> > > 
> > > 
> > > 你呢，websocket稳定和发送失败都搞不定，在这里秀，只是觉得你智商低能力差，不想搭理你还在那里叫唤。
> > 
> > 
> > 哈哈哈哈哈。这还不是破防了啊？这就是你所谓得正常讨论技术啊？哈哈哈，说到你痛处了吧，一连发了好几个脏话，太可怜了。你是最聪明的 全天下你最聪明
> 
> 本来没骂你，你自己凑过来找骂的，你连协议稳定安全，失败怎么处理都不知道 ，就别秀了好吗？也没邀请你过来回答，你一张口给我逗笑了，所以你能力和智商有问题。

别几把叭叭了曹尼玛的傻逼快回老家给你爹妈哭坟去吧

**Comment by give0923** [comment]
> > > > > > > > 你脑子不好是吧
> > > > > > > 
> > > > > > > 
> > > > > > > 呦呵，又来一位脑残
> > > > > > 
> > > > > > 
> > > > > > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> > > > > 
> > > > > 
> > > > > 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限
> > > > 
> > > > 
> > > > 你这个也叫做技术讨论啊？哈哈哈哈哈 直接破防了骂人了还叫做技术讨论 hhh
> > > 
> > > 
> > > 你呢，websocket稳定和发送失败都搞不定，在这里秀，只是觉得你智商低能力差，不想搭理你还在那里叫唤。
> > 
> > 
> > 哈哈哈哈哈。这还不是破防了啊？这就是你所谓得正常讨论技术啊？哈哈哈，说到你痛处了吧，一连发了好几个脏话，太可怜了。你是最聪明的 全天下你最聪明
> 
> 本来没骂你，你自己凑过来找骂的，你连协议稳定安全，失败怎么处理都不知道 ，就别秀了好吗？也没邀请你过来回答，你一张口给我逗笑了，所以你能力和智商有问题。

你这种臭傻逼还真的自以为是，总觉得自己很牛逼的样子。你眼睛瞎了？你吐出来的大便你看不见？

**Comment by give0923** [comment]
> > > > > > > > 你脑子不好是吧
> > > > > > > 
> > > > > > > 
> > > > > > > 呦呵，又来一位脑残
> > > > > > 
> > > > > > 
> > > > > > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> > > > > 
> > > > > 
> > > > > 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限
> > > > 
> > > > 
> > > > 你这个也叫做技术讨论啊？哈哈哈哈哈 直接破防了骂人了还叫做技术讨论 hhh
> > > 
> > > 
> > > 你呢，websocket稳定和发送失败都搞不定，在这里秀，只是觉得你智商低能力差，不想搭理你还在那里叫唤。
> > 
> > 
> > 哈哈哈哈哈。这还不是破防了啊？这就是你所谓得正常讨论技术啊？哈哈哈，说到你痛处了吧，一连发了好几个脏话，太可怜了。你是最聪明的 全天下你最聪明
> 
> 本来没骂你，你自己凑过来找骂的，你连协议稳定安全，失败怎么处理都不知道 ，就别秀了好吗？也没邀请你过来回答，你一张口给我逗笑了，所以你能力和智商有问题。

真的不想骂你的，哪知道你屎吃多了 收不住。你的问题就是bc级别的 还在那里蹦跶，小丑你自个玩吧。自己破防了满地喷粪 还优越感十足 真的笑了

**Comment by dingchunqiuzyz** [comment]
> > > > > > > > > 你脑子不好是吧
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 呦呵，又来一位脑残
> > > > > > > 
> > > > > > > 
> > > > > > > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> > > > > > 
> > > > > > 
> > > > > > 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限
> > > > > 
> > > > > 
> > > > > 你这个也叫做技术讨论啊？哈哈哈哈哈 直接破防了骂人了还叫做技术讨论 hhh
> > > > 
> > > > 
> > > > 你呢，websocket稳定和发送失败都搞不定，在这里秀，只是觉得你智商低能力差，不想搭理你还在那里叫唤。
> > > 
> > > 
> > > 哈哈哈哈哈。这还不是破防了啊？这就是你所谓得正常讨论技术啊？哈哈哈，说到你痛处了吧，一连发了好几个脏话，太可怜了。你是最聪明的 全天下你最聪明
> > 
> > 
> > 本来没骂你，你自己凑过来找骂的，你连协议稳定安全，失败怎么处理都不知道 ，就别秀了好吗？也没邀请你过来回答，你一张口给我逗笑了，所以你能力和智商有问题。
> 
> 真的不想骂你的，哪知道你屎吃多了 收不住。你的问题就是bc级别的 还在那里蹦跶，小丑你自个玩吧。自己破防了满地喷粪 还优越感十足 真的笑了

你是技术菜又情商低，不是骂你自己凑过来找骂了，跟你这智障没什么好聊的。

**Comment by dingchunqiuzyz** [comment]
> > > > > > > > > 你脑子不好是吧
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 呦呵，又来一位脑残
> > > > > > > 
> > > > > > > 
> > > > > > > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> > > > > > 
> > > > > > 
> > > > > > 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限
> > > > > 
> > > > > 
> > > > > 你这个也叫做技术讨论啊？哈哈哈哈哈 直接破防了骂人了还叫做技术讨论 hhh
> > > > 
> > > > 
> > > > 你呢，websocket稳定和发送失败都搞不定，在这里秀，只是觉得你智商低能力差，不想搭理你还在那里叫唤。
> > > 
> > > 
> > > 哈哈哈哈哈。这还不是破防了啊？这就是你所谓得正常讨论技术啊？哈哈哈，说到你痛处了吧，一连发了好几个脏话，太可怜了。你是最聪明的 全天下你最聪明
> > 
> > 
> > 本来没骂你，你自己凑过来找骂的，你连协议稳定安全，失败怎么处理都不知道 ，就别秀了好吗？也没邀请你过来回答，你一张口给我逗笑了，所以你能力和智商有问题。
> 
> 别几把叭叭了曹尼玛的傻逼快回老家给你爹妈哭坟去吧

你是真傻比，后面在评论自己看吧，帖子我关了。

**Comment by give0923** [comment]
> > > > > > > > > > 你脑子不好是吧
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 呦呵，又来一位脑残
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 废物东西傻逼东西，我给你脸了是吧？狗吗？不会好好说话，这么急
> > > > > > > 
> > > > > > > 
> > > > > > > 很正常的一个技术讨论，也没邀请你们两条狗，过来就狗叫，还秀你们的技术下限
> > > > > > 
> > > > > > 
> > > > > > 你这个也叫做技术讨论啊？哈哈哈哈哈 直接破防了骂人了还叫做技术讨论 hhh
> > > > > 
> > > > > 
> > > > > 你呢，websocket稳定和发送失败都搞不定，在这里秀，只是觉得你智商低能力差，不想搭理你还在那里叫唤。
> > > > 
> > > > 
> > > > 哈哈哈哈哈。这还不是破防了啊？这就是你所谓得正常讨论技术啊？哈哈哈，说到你痛处了吧，一连发了好几个脏话，太可怜了。你是最聪明的 全天下你最聪明
> > > 
> > > 
> > > 本来没骂你，你自己凑过来找骂的，你连协议稳定安全，失败怎么处理都不知道 ，就别秀了好吗？也没邀请你过来回答，你一张口给我逗笑了，所以你能力和智商有问题。
> > 
> > 
> > 真的不想骂你的，哪知道你屎吃多了 收不住。你的问题就是bc级别的 还在那里蹦跶，小丑你自个玩吧。自己破防了满地喷粪 还优越感十足 真的笑了
> 
> 你是技术菜又情商低，不是骂你自己凑过来找骂了，跟你这智障没什么好聊的。

你真的需要睁大你的g眼看看，你谁先吐大便的。你怎么会问这么shab的问题啊？还优越感十足，没人教你吗？还好意思说正常技术讨论，讨论nm呢，快回去苦吧，又菜嘴还臭
